# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chord.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\"/\n\x0fRegisterRequest\x12\x0e\n\x06ipaddr\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\",\n\rRegisterReply\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x11\x44\x65registerRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"2\n\x0f\x44\x65registerReply\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x1aPopulateFingerTableRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"B\n\x18PopulateFingerTableReply\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x1a\n\x0b\x66ingerTable\x18\x02 \x03(\x0b\x32\x05.Node\"\x15\n\x13getChordInfoRequest\")\n\x11getChordInfoReply\x12\x14\n\x05nodes\x18\x01 \x03(\x0b\x32\x05.Node\"\"\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06ipaddr\x18\x02 \x01(\t2\x80\x02\n\x0bInnoService\x12.\n\x08register\x12\x10.RegisterRequest\x1a\x0e.RegisterReply\"\x00\x12\x34\n\nderegister\x12\x12.DeregisterRequest\x1a\x10.DeregisterReply\"\x00\x12O\n\x13populateFingerTable\x12\x1b.PopulateFingerTableRequest\x1a\x19.PopulateFingerTableReply\"\x00\x12:\n\x0cgetChordInfo\x12\x14.getChordInfoRequest\x1a\x12.getChordInfoReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chord_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERREQUEST._serialized_start=15
  _REGISTERREQUEST._serialized_end=62
  _REGISTERREPLY._serialized_start=64
  _REGISTERREPLY._serialized_end=108
  _DEREGISTERREQUEST._serialized_start=110
  _DEREGISTERREQUEST._serialized_end=141
  _DEREGISTERREPLY._serialized_start=143
  _DEREGISTERREPLY._serialized_end=193
  _POPULATEFINGERTABLEREQUEST._serialized_start=195
  _POPULATEFINGERTABLEREQUEST._serialized_end=235
  _POPULATEFINGERTABLEREPLY._serialized_start=237
  _POPULATEFINGERTABLEREPLY._serialized_end=303
  _GETCHORDINFOREQUEST._serialized_start=305
  _GETCHORDINFOREQUEST._serialized_end=326
  _GETCHORDINFOREPLY._serialized_start=328
  _GETCHORDINFOREPLY._serialized_end=369
  _NODE._serialized_start=371
  _NODE._serialized_end=405
  _INNOSERVICE._serialized_start=408
  _INNOSERVICE._serialized_end=664
# @@protoc_insertion_point(module_scope)
